{{- if .Values.manager.ingress.enable -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "dragonfly.manager.fullname" . }}
  labels:
    app: {{ template "dragonfly.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.manager.name }}
{{- if .Values.manager.ingress.annotations }}
  annotations:
{{ toYaml .Values.manager.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.manager.ingress.className }}
  ingressClassName: {{ .Values.manager.ingress.className | quote }}
  {{- end }}
{{- if .Values.manager.ingress.tls }}
  tls:
  {{- range .Values.manager.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.manager.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.manager.ingress.path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service: 
                name: {{ template "dragonfly.manager.fullname" $ }}
                port: 
                  number: {{ $.Values.manager.restPort }}
  {{- end }}
{{- end }}
